message(Sys.time(), "\n\n")
decolonize <- function(tm) {
  tm <- gsub("[-:]", "_", tm)
  gsub(" ", "__", tm)
}

suppressPackageStartupMessages(
  library(loggit)
)

set_logfile(
  glue::glue(
    "{getwd()}/log/shadow_backup_{decolonize(Sys.time())}.log"
  )
)

message("Execution start")

source("secret.R")
source("initializers.R")

suppressPackageStartupMessages({
  library(dplyr)
})

repos <- "../shadow-backups"

loggit(
  "INFO",
  "Repo status",
  output = capture.output(git2r::status(repos)) %>% 
    paste(collapse = "\n") %>% 
    stringr::str_replace_all("\n|\r", "<br>") %>% 
    stringr::str_replace_all(":", "-")
  )

git2r::config(
  repo = git2r::repository(repos),
  user.name = "shadow_db_backup_bot",
  user.email = "brianwdavis@gmail.com"
)


etl_dump <- function(db_name, tbl_name) {
  out <- glue::glue("../shadow-backups/{db_name}_{tbl_name}.sql")
  
  system2(
    "sqlite3",
    args = c(
      glue::glue("./db/{db_name}.db"), 
      glue::glue("'.dump {tbl_name}'")
      ),
    stdout = out
  )

  info <- file.info(out)
  
  age <- as.double(
    Sys.time() - info$mtime, 
    units = "secs"
    )
  
  if (age > 10 || is.na(age) || is.null(age)) {
    warning("File `", basename(out), "` was not written during this call.")
    }
  
  #tibble(table = tbl_name, size = info$size, last_stored = info$mtime)
  loggit(
    "INFO", glue::glue("Dump"), 
    db = db_name, file = tbl_name, size = info$size, last_stored = info$mtime
    )
}




con_sh_f <- etl_connect_shadow("forms")


message("Dumping forms")
DBI::dbListTables(con_sh_f) %>% 
  purrr::map(~etl_dump("forms", .x))

message("Forms dump completed")

dbDisconnect(con_sh_f)




con_sh_s <- etl_connect_shadow("sensors")

message("Dumping sensors")
DBI::dbListTables(con_sh_s) %>% 
  purrr::walk(~etl_dump("sensors", .x)) 

message("Sensors dump completed")


dbDisconnect(con_sh_s)



loggit(
  "INFO",
  "Repo status",
  output = capture.output(git2r::status(repos)) %>% 
    paste(collapse = "\n") %>% 
    stringr::str_replace_all("\n|\r", "<br>") %>% 
    stringr::str_replace_all(":", "-")
)

git2r::add(
  repo = repos,
  path = "*.sql"
)
message("`git add`ed all *.sql files")


s <- git2r::status(repos)
s

loggit(
  "INFO",
  "Repo status",
  output = capture.output(s) %>% 
    paste(collapse = "\n") %>% 
    stringr::str_replace_all("\n|\r", "<br>") %>% 
    stringr::str_replace_all(":", "-")
)

l <- s[c("staged", "unstaged")] %>% 
  purrr::map_int(length)

sess <- sessionInfo()
sys <- Sys.info()

if (sum(l)) {
  cmt <- capture.output(
    git2r::commit(
      repo = repos,
      message = glue::glue(
        "Automated backup at {Sys.time()}\n\n",
        R.version.string,
        "\n{sess$platform}\n{sess$running}",
        "\n{sys['nodename']}\n{sys['user']}"
      ),
      all = TRUE
    )
  ) %>% paste(collapse = "\n") %>% 
    stringr::str_replace_all("\n|\r", "<br>") %>% 
    stringr::str_replace_all(":", "-")
  
  loggit(
    "INFO",
    "Repo commit",
    output = cmt
  )
} else {
  message("Nothing to commit!")
}

# git2r::remote_add(
#   repo = repos,
#   name = "shadow-backups-remote",
#   url = "https://github.com/precision-sustainable-ag/shadow-backups.git"
# )


git2r::push(
  object = repos,
  name = "shadow-backups-remote",
  refspec = "refs/heads/master",
  credentials = git2r::cred_user_pass(
    username = "brianwdavis",
    password = gh_token
  )
)
message("Pushed to GH remote")

message("Execution end")

set_logfile(logfile = NULL, confirm = TRUE)


# Generate README for shadow-backup repo ----
#
# writeLines(
#   c(
#     "# Structure",
#     "Each file is a dump generated by calling: ", "",
#     "`sqlite3 .dump {table_name} > {db_name}_{table_name}.sql`",
#     "# Origin",
#     "These files are automatically generated by the script at:", "",
#     "`<link to ETL repo coming...>`"
#   ),
#   file.path(repos, "README.md")
# )
# git2r::add(
#   repos,
#   "README.md"
# )


